markdown: kramdown
highlighter: rogue
exclude: ['Rakefile', 'blog.ipr', 'blog.iws', 'blog.iml']
blog:
    title: RealityForge.org
    subtitle: A little short for a storm trooper
    url: http://realityforge.org
    author: Peter Donald
    email: peter@realityforge.org
